---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-feature-discovery
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 0.16.3
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    prometheus:
      enable: false
    master:
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
    worker:
      config:
        core:
          sources: [custom, pci, usb]
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
