---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: crunchy-pgo-cluster-vector
    - name: dragonfly-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/selfhosted/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: immich
