---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app change-detection
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/selfhosted/change-detection/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: changedetection
      VOLSYNC_CAPACITY: 1Gi
