---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1sms0pnuz0hylr53gvj49mt3vvfypsg572lu2lh3fajvlkmp2gpuq9y5yk7"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1sms0pnuz0hylr53gvj49mt3vvfypsg572lu2lh3fajvlkmp2gpuq9y5yk7"
