---
originRequest:
  http2Origin: true

ingress:
  - hostname: "${SECRET_DOMAIN_LOCAL}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN_LOCAL}"
  - hostname: "*.${SECRET_DOMAIN_LOCAL}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN_LOCAL}"
  - hostname: "${SECRET_DOMAIN_PERSONAL}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN_PERSONAL}"
  - hostname: "*.${SECRET_DOMAIN_PERSONAL}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN_PERSONAL}"
  - hostname: "${SECRET_DOMAIN_PUBLIC}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN_PUBLIC}"
  - hostname: "*.${SECRET_DOMAIN_PUBLIC}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.${SECRET_DOMAIN_PUBLIC}"
  - service: http_status:404
