---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app change-detection
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      change-detection:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: latest@sha256:13506a87ab427c7604733675a7af059fc6f996cf4fd1dc16cc6de514472e68fa
            env:
              TZ: ${TIMEZONE}
              BASE_URL: https://changedetection.${SECRET_DOMAIN_LOCAL}
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: "ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/tmp/cache"
            resources:
              requests:
                cpu: 25m
                memory: 145M
              limits:
                memory: 512M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
          browserless:
            image:
              repository: ghcr.io/browserless/chrome
              tag: latest@sha256:3c86bcc0f0155daeb196ba0baa2db1e5dfc143d90f9c209267113f98f5cba065
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              CONNECTION_TIMEOUT: 300000
              SCREEN_WIDTH: 1920
              SCREEN_HEIGHT: 1024
              SCREEN_DEPTH: 16
              ENABLE_DEBUGGER: false
              PREBOOT_CHROME: true
              MAX_CONCURRENT_SESSIONS: 10
              CHROME_REFRESH_TIME: 600000
              DEFAULT_BLOCK_ADS: true
              DEFAULT_STEALTH: true
            resources:
              requests:
                cpu: 25m
                memory: 979M
              limits:
                memory: 1G
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN_LOCAL}
        hosts:
          - host: "changedetection.${SECRET_DOMAIN_LOCAL}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: change-detection
        advancedMounts:
          change-detection:
            app:
              - path: /datastore
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
