---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: change-detection
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
