---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-pgo-vector
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: crunchy-pgo-vector-secret
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .CRUNCHY_AWS_ACCESS_KEY_ID }}
          repo1-s3-key-secret={{ .CRUNCHY_AWS_SECRET_ACCESS_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: crunchy-pgo
    - extract:
        key: minio-storage
