---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sabnzbd
  namespace: flux-system
spec:
  targetNamespace: downloads
  dependsOn:
    - name: external-secrets-stores
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/downloads/sabnzbd/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: sabnzbd
      VOLSYNC_CLAIM: sabnzbd-config
      VOLSYNC_CAPACITY: 1Gi
