apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1J5OZvr3EWX1N9pzGOU+IkVbyoHO7hlLcsknf2IOD6LNRqa2,iv:PagTiFVTlOIv+nGrW9YuwXeAgdR7fadQIOMcejoB9/A=,tag:Bdq1VOPwrHEr3SSsABFzyQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:YoENk7waAKXgyR4Bg1dIYZ6k6mVzB5g05J3m3yu1JVwGyByapaAJuO01qxqHKiW68ESCJsalQ1Rm8iD+aI/BAv4HlLHu+jEal5rGb5XbYaknMYs6AHtcE6QWDtaqUulTtSAifPCKWfxnu4haRPKK/kQRfRdW/oO3j0iIDo0BHWsgKVNg+yQ+esHuzkuez/C5jSCOByca3HxzYn3WAn8kUtZsw7XxNMhtrvjLUkHkdQ==,iv:Kj14xIN54MwuOTGK8ae+kf8z0qJusGiIiroH50uQ1BQ=,tag:7pCnd3/8lczI9jzr/ZZb3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sms0pnuz0hylr53gvj49mt3vvfypsg572lu2lh3fajvlkmp2gpuq9y5yk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VnBzU1E2ODJ3Y0RmRTk3
            SVo5Wjk3Y0VKRWd1YWRjOHl3NkkvZE0wZ3lzCkxqZVk3KzR0L2pzcVphb0VYd0tK
            TE5ldmhVRGpoUnFySWVtVVgrOER0NkUKLS0tIHgzclhPalVvTWRNVXYwcGd4VmF2
            QVBkNGZYemtsS0QyNit0M3FVQTVDNEUK/4337V57GRBirfnoQgSssMabHP6pTzrp
            SDhOE9Wst3VppZc/V3ckM0VJicJzEbaYiG02McdqUB9bUTDN1U48cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T05:47:22Z"
    mac: ENC[AES256_GCM,data:I0SZGLWwPIigp9i7V+xYIQimGgTsJituYdFis/TS2gGRDQSttJQr8iWrg3q9dugjuURk6WMehh11rgbOo3su2F5FdDkU0/dQQC1aaMSdej0VXE+H4ZTfw7E42ZsFWgo0GJDMriZZ5unW7JhW69DC/+KvLEuDRmuC6UK7jWEehVI=,iv:MkYtjMbbqGVzATArHxO3rRQyyhXGdGlpRWNMRBnOU0U=,tag:6jzKs+s9jJl9PcIhjrgFoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
