---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wizarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      wizarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository:  ghcr.io/wizarrrr/wizarr
              tag: 4.1.1
            env:
              TZ: Pacific/Auckland
            resources:
              requests:
                cpu: 15m
                memory: 180M
              limits:
                memory: 300M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5690
    ingress:
      app:
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Video
          gethomepage.dev/name: Wizarr
          gethomepage.dev/icon: wizarr.png
          gethomepage.dev/description: Jellyfin Invite Management
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN_PUBLIC}
        hosts:
          - host: join.${SECRET_DOMAIN_PUBLIC}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: wizarr-config
        globalMounts:
          - path: /data/database
