---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name vikunja-secret
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        VIKUNJA_SERVICE_JWTSECRET: "{{ .VIKUNJA_SERVICE_JWTSECRET }}"
        VIKUNJA_REDIS_HOST: dragonfly.databases.svc.cluster.local:6379
        VIKUNJA_DATABASE_HOST: postgres16-rw.databases.svc.cluster.local
        VIKUNJA_DATABASE_DATABASE: vikunja
        VIKUNJA_DATABASE_USER: "{{ .VIKUNJA_POSTGRES_USER }}"
        VIKUNJA_DATABASE_PASSWORD: "{{ .VIKUNJA_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: vikunja
