---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-metadata
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 350Gi
  storageClassName: ceph-block
