---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cpgo-gatus
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: cpgo
        group: infrastructure
        url: tcp://postgres-pgbouncer.databases.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
