---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-pgo
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/databases/crunchy-pgo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-pgo-cluster
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-pgo
    - name: external-secrets-stores
  path: ./kubernetes/apps/databases/crunchy-pgo/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-pgo-cluster-vector
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-pgo
    - name: external-secrets-stores
  path: ./kubernetes/apps/databases/crunchy-pgo/cluster-vector
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-pgo-secrets
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
  path: ./kubernetes/apps/databases/crunchy-pgo/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-pgo-users
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-pgo
  path: ./kubernetes/apps/databases/crunchy-pgo/users
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
