---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: selfhosted
data:
  # URLS
  IMMICH_SERVER_URL: http://immich-server.selfhosted.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.selfhosted.svc.cluster.local:3003
  PUBLIC_IMMICH_SERVER_URL: https://immich.${SECRET_DOMAIN_PERSONAL}
  # SETTINGS
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: log
  NODE_ENV: production
  IMMICH_MEDIA_LOCATION: /photos
  UPLOAD_LOCATION: /photos/upload
  # REDIS
  REDIS_HOSTNAME: dragonfly.databases.svc.cluster.local
  REDIS_DBINDEX: "1"
  REDIS_PORT: "6379"
