---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 15m
  target:
    name: immich-secret
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .IMMICH_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: immich
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 15m
  target:
    name: immich-db-secret
    template:
      engineVersion: v2
      data:
        DB_URL: "{{ .DB_URL }}"
  dataFrom:
    - extract:
        key: postgres-vector-pguser-immich
