---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: bazarr-secret
    template:
      engineVersion: v2
      data:
        BAZARR__API_KEY: "{{ .BAZARR_API_KEY }}"
  dataFrom:
  - extract:
      key: bazarr
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: bazarr-db-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_ENABLED: "true"
        POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        POSTGRES_USERNAME: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_DATABASE: '{{ index . "dbname" }}'
  dataFrom:
  - extract:
      key: postgres-pguser-bazarr
