---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__AUTH__APIKEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
  - extract:
      key: prowlarr
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: prowlarr-db-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__POSTGRES__HOST: '{{ index . "pgbouncer-host" }}'
        PROWLARR__POSTGRES__PORT: '{{ index . "pgbouncer-port" }}'
        PROWLARR__POSTGRES__USER: '{{ index . "user" }}'
        PROWLARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        PROWLARR__POSTGRES__MAINDB: '{{ index . "dbname" }}'
  dataFrom:
  - extract:
      key: postgres-pguser-prowlarr
