---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_TOKEN: "{{ HOMEPAGE_TOKEN }}"
        HOMEPAGE_LATITUDE: "{{ HOMEPAGE_LATITUDE }}"
        HOMEPAGE_LONGITUDE: "{{ HOMEPAGE_LONGITUDE }}"
        TEST_NAME: "{{ TEST_NAME }}"
  dataFrom:
  - extract:
      key: homepage
  - extract:
      key: secret
