---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Downloads
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        ## Home
        HOMEPAGE_VAR_HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HOMEPAGE_VAR_HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HOMEPAGE_VAR_GLANCES_USERNAME: "{{ .GLANCES_USERNAME }}"
        HOMEPAGE_VAR_GLANCES_PASSWORD: "{{ .GLANCES_PASSWORD }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UNIFI_USERNAME }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNIFI_PASSWORD }}"
  dataFrom:
  - extract:
      key: glances
  - extract:
      key: homepage
  - extract:
      key: prowlarr
  - extract:
      key: radarr
  - extract:
      key: sabnzbd
  - extract:
      key: sonarr
