---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./external-secrets/bitwarden-secrets-manager/ks.yaml
  - ./external-secrets/external-secrets/ks.yaml
