---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-images-pvc
  namespace: selfhosted
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
