---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-images-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
  storageClassName: ceph-block
