---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_LOCAL/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN_LOCAL/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_LOCAL}"
  dnsNames:
    - "${SECRET_DOMAIN_LOCAL}"
    - "*.${SECRET_DOMAIN_LOCAL}"
    - "${SECRET_DOMAIN_PERSONAL}"
    - "*.${SECRET_DOMAIN_PERSONAL}"
    - "${SECRET_DOMAIN_PUBLIC}"
    - "*.${SECRET_DOMAIN_PUBLIC}"
