---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app amd-gpu-node-labeller
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: amd-device-plugin
      namespace: kube-system
  values:
    controllers:
      amd-gpu-node-labeller:
        type: daemonset
        containers:
          app:
            image:
              repository: docker.io/rocm/k8s-device-plugin
              tag: labeller-1.25.2.3
            workingDir: /root
            command: ["/root/k8s-node-labeller"]
            args:
              [
                "-logtostderr=true",
                "-stderrthreshold=INFO",
                "-v=5",
                "-vram",
                "-cu-count",
                "-simd-count",
                "-device-id",
                "-family",
              ]
            env:
              TZ: ${TIMEZONE}
              DS_NODE_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            securityContext:
              privileged: true
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 100Mi
    defaultPodOptions:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        feature.node.kubernetes.io/pci-0300_1002.present: "true"
        kubernetes.io/arch: amd64
      priorityClassName: system-node-critical
    serviceAccount:
      create: false
      name: amd-gpu-node-labeller
    service:
      app:
        enabled: false
        controller: amd-gpu-node-labeller
    persistence:
      sys:
        enabled: true
        type: hostPath
        hostPath: /sys
      dev:
        enabled: true
        type: hostPath
        hostPath: /dev
