---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 15m
  target:
    name: linkding-db-secret
    template:
      engineVersion: v2
      data:
        LD_DB_HOST: '{{ index . "pgbouncer-host" }}'
        LD_DB_PORT: '{{ index . "pgbouncer-port" }}'
        LD_DB_USER: '{{ index . "user" }}'
        LD_DB_PASSWORD: '{{ index . "password" }}'
        LD_DB_DATABASE: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-linkding
