---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app linkding
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      linkding:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/sissbruecker/linkding
              tag: 1.36.0
            env:
              TZ: ${TIMEZONE}
              LD_DISABLE_BACKGROUND_TASKS: false
              LD_DISABLE_URL_VALIDATION: false
              LD_DB_ENGINE: postgres
              LD_CSRF_TRUSTED_ORIGINS: "https://bookmarks.${SECRET_DOMAIN_PERSONAL}"
            envFrom:
              - secretRef:
                  name: linkding-db-secret
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: linkding
        ports:
          http:
            port: 9090
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN_PERSONAL}
        hosts:
          - host: "bookmarks.${SECRET_DOMAIN_PERSONAL}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: linkding
        globalMounts:
          - path: /etc/linkding/data
