apiVersion: v1
kind: Secret
metadata:
    name: bws-secret
    labels:
        external-secrets.io/type: webhook
stringData:
    token: ENC[AES256_GCM,data:R2irhEMUkKI47YhcvB24GQmgJCjkSm3A46r2WzojYRgAu5ysWos0KpDtZpOLtMrd84DsebwhkWn2ocVfmD++3/o4GcmQZn/rveyvQBiFfRvGwZ60wIAr+tKuPjSmyQ==,iv:SSZgBsKELzJEPf8YQUBZV83sTRBTa70NfoT0hF4pdqA=,tag:yvRidGWn1JsiPLZUPB4a8Q==,type:str]
    ORG_ID: ENC[AES256_GCM,data:bQla7/Z3vX0lEDtfYFjHZnxFxPVLUglGNADzbmVTl2PiBDBe,iv:DzUwgwnltzxNLUP0X1mD5CwylawkQJ6tIsMZaeLTcek=,tag:OK4pIe8ujFpGQ1FyHyBNVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sms0pnuz0hylr53gvj49mt3vvfypsg572lu2lh3fajvlkmp2gpuq9y5yk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVl5TkdObldMQ2pvQUlx
            aVRackdRSFJ3bmovSTVoUW1KY3JWQStaTW1JCkYyMlJGRHdXcmVJTEdKSU1nVHJV
            R3R4UDhETWpKdmpVL2tNQk01aDhFbFkKLS0tIERreUJKMmM1MWhDbjdjZVltK2lV
            Y1p1TjZlTjUxM0JsTC8vWWxVZG9EMmMKbzFrZr8wJA1DG8FfJ4zNqe3HZrBK1N5U
            wfkKFh02Uo4bfIBuzbokivdrBVkKT0I+oBK1z5bnCPugSKpvRrg9Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T07:10:30Z"
    mac: ENC[AES256_GCM,data:d3sKO1vGfHZuEj0v42uPSsVg1fyNO3KnouKGIo/i53cwGyG3xk6O0HQUQAvrwpWBBnU3dH46lqX3Z+KmUu2ev9qPSlUNDR1sFqqPKWGQOTiWYOkjhH/cRp0fgj+W75BknhYA2u/HjHWeyFdpCqZrBLgVXpfestBgXX4Z2hW1+bU=,iv:Unsj6/d/Fak+NKmTAb6wncaiKatdsLDIqnrI+91GEYA=,tag:4gnh9+CCSYo5/Ycrgyxd0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
