---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name enshrouded-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SERVER_PASSWORD: "{{ .SERVER_PASSWORD }}"
        enshrouded_server.json: |-
          {
            "name": "Pigs of Garbage",
            "saveDirectory": "./savegame",
            "logDirectory": "./logs",
            "ip": "0.0.0.0",
            "gamePort": 15636,
            "queryPort": 15637,
            "slotCount": 16,
            "gameSettingsPreset": "Relaxed",
            "gameSettings": {
              "playerHealthFactor": 1,
              "playerManaFactor": 1,
              "playerStaminaFactor": 1.5,
              "playerBodyHeatFactor": 1,
              "enableDurability": true,
              "enableStarvingDebuff": true,
              "foodBuffDurationFactor": 1,
              "fromHungerToStarving": 600000000000,
              "shroudTimeFactor": 1,
              "tombstoneMode": "AddBackpackMaterials",
              "enableGliderTurbulences": true,
              "weatherFrequency": "Normal",
              "miningDamageFactor": 1,
              "plantGrowthSpeedFactor": 1,
              "resourceDropStackAmountFactor": 1,
              "factoryProductionSpeedFactor": 2,
              "perkUpgradeRecyclingFactor": 0.5,
              "perkCostFactor": 1.5,
              "experienceCombatFactor": 0.5,
              "experienceMiningFactor": 0.25,
              "experienceExplorationQuestsFactor": 0.25,
              "randomSpawnerAmount": "Extreme",
              "aggroPoolAmount": "Few",
              "enemyDamageFactor": 1,
              "enemyHealthFactor": 1,
              "enemyStaminaFactor": 1,
              "enemyPerceptionRangeFactor": 2,
              "bossDamageFactor": 1,
              "bossHealthFactor": 1.5,
              "threatBonus": 1,
              "pacifyAllEnemies": false,
              "tamingStartleRepercussion": "LoseSomeProgress",
              "dayTimeDuration": 1800000000000,
              "nightTimeDuration": 600000000000
            },
            "userGroups": [
              {
                "name": "Admin",
                "password": "{{ .admin_group_password }}",
                "canKickBan": true,
                "canAccessInventories": true,
                "canEditBase": true,
                "canExtendBase": true,
                "reservedSlots": 1
              },
              {
                "name": "Pigs",
                "password": "{{ .user_group_password }}",
                "canKickBan": false,
                "canAccessInventories": true,
                "canEditBase": true,
                "canExtendBase": true,
                "reservedSlots": 3
              }
            ]
          }
  dataFrom:
  - extract:
      key: enshrouded
