# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-pog
spec:
  interval: 30m
  chart:
    spec:
      chart: minecraft
      version: 4.23.2
      sourceRef:
        kind: HelmRepository
        name: itzg-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: itzg/minecraft-server
      tag: stable
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 12Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - echo
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      TZ: ${TIMEZONE}
      MEMORY: ""
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: &host mcpog.${SECRET_DOMAIN_PUBLIC}
    minecraftServer:
      eula: true
      version: 1.21.1
      type: PAPER
      difficulty: hard
      whitelist: "duckieyumie,WingsGB,AspastIIcBean,Taytaymademegay,blm7272,pongu69"
      ops: "WingsGB"
      pvp: true
      motd: "Be Garbage"
      viewDistance: 32
      forceReDownload: true
      memory: ""
      jvmXXOpts: "-XX:MaxRAMPercentage=70 -Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar --nogui"
      # spigetResources:
      #   - 36618
      #   # Dynmap
      #   - 274
      rcon:
        enabled: true
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          ingressClassName: external
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: mc.${SECRET_DOMAIN_PUBLIC}
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
           - name: *host
  valuesFrom:
  - kind: Secret
    name: minecraft-mcpog-secret
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password
