# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-pog
spec:
  interval: 30m
  chart:
    spec:
      chart: minecraft
      version: 4.23.2
      sourceRef:
        kind: HelmRepository
        name: itzg-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: itzg/minecraft-server
      tag: stable
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 16Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - echo
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      TZ: ${TIMEZONE}
      MEMORY: ""
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: &host mcpog.${SECRET_DOMAIN_PUBLIC}
    minecraftServer:
      eula: true
      version: 1.21.1
      type: PAPER
      difficulty: hard
      whitelist: "8ec03a15-8380-4ebe-9b18-2446d5c6e821,cdf8251d-5ddc-4453-acab-8ca919aae5c5,0ae19002-33fa-4d0b-af12-366472a4e4df,23781a8d-ecf4-4a8a-8dfe-a3b77ca31bf8,6d9bf4fb-b980-4dd1-9dd4-8c32e400f2b9,2a9bb4a5-f365-4205-8f4b-addeadaedb0d"
      ops: "cdf8251d-5ddc-4453-acab-8ca919aae5c5"
      pvp: true
      motd: "Be Garbage"
      viewDistance: 32
      forceReDownload: true
      memory: ""
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      spigetResources:
        # ProtocolLib
        - 1997
        # ChestSort
        - 59773
        # ResurrectionChest
        - 57541
        # Simple Elevators
        - 44462
        # Chunky
        - 81534
        # Dynmap
        - 274
        # GSit
        - 62325
      rcon:
        enabled: true
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          ingressClassName: external
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: mc.${SECRET_DOMAIN_PUBLIC}
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
           - name: *host
  valuesFrom:
  - kind: Secret
    name: minecraft-mcpog-secret
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password
