---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name radarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"
  dataFrom:
  - extract:
      key: radarr
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-db
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: &name radarr-db-secret
    template:
      engineVersion: v2
      data:
        RADARR__POSTGRES__HOST: '{{ index . "pgbouncer-host" }}'
        RADARR__POSTGRES__PORT: '{{ index . "pgbouncer-port" }}'
        RADARR__POSTGRES__USER: '{{ index . "user" }}'
        RADARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        RADARR__POSTGRES__MAINDB: '{{ index . "dbname" }}'
  dataFrom:
  - extract:
      key: postgres-pguser-radarr
