---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: internal
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "${APP}.${SECRET_DOMAIN_PERSONAL}"
          query-type: A
        conditions:
          - "len([BODY]) == 0"
