---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app linkding
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: crunchy-pgo-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/selfhosted/linkding/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: bookmarks
      VOLSYNC_CAPACITY: 512Mi
