apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nI2XVy0kTKv8rtKRkg==,iv:KO8M80ibuHwm2/h3eU6iAKJiVf1Um5fojns4tXVsbmg=,tag:mc+6HlrcS8gmjMGVZMtzVQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Hh52SHl9yw+Fxz6zdkh+Qv6/R1KD2S1EWw==,iv:EOpHGdBHR3lfKG0249iPZsXv5Z24EjoUgGEnlsw3W/g=,tag:AY6+XDqhOza3A+GVvqkt2w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:a7pCG0sn2iD9JR5V2p3Jp8TzpSrHSokGN5tfB8FOLmbBuQPu,iv:Jln1fUo0LIztFVhy8hIhlWzNpBTQ9J0pGG3BHg/5QPE=,tag:LjB6RrNKQVK45QLHwoyJrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yquhz76hg30kccyycwjzj2zxhz5f4phllu470yp9ltjee97wrd2sgkmz0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcXRGY005SThtNnBGVlRV
            N0duUXA4U1U0anZUbURHc1lidmJHeCtsWlN3ClZNbllZdFpKUkVXM1FLempnSXdl
            ZVhEd3A1NXJnTUdKWHhIMVRlWi8wUzgKLS0tIElTOFo5SlR6bEl5MHdZaW5sTnY5
            R0NOOXc0VVNhRG1Ic2lNTGlZeVBuT1EKgo+Df1WajZPichhbzQ7NHd3CCAGFnXZa
            QuebYzqBUJtvhoLWmgjDKjB5+9jm5yFMl+2cqXPaTPCFjzvsmhQTOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T03:25:19Z"
    mac: ENC[AES256_GCM,data:VHVpOe/VV4TAmKtoFs8tAbM3f8Al40u/HdWyxzW5vMe3THK65xymKlo14kQlvmWLERUh0TE7W4iNfWt98wm9oArRKe+o3T12jUkf2+lFuJB2IMoRTy5ouVPrTBJzahAo0JlxbHhBcRjxtYFXI1RErjlgiG40fBu7/sebvNJDYgg=,iv:u3MpSwqlUZlwJ5ZclCy2fPS1hE8XwXvyAZRFy0sLvrI=,tag:kTf4QnurBRl8p1CmS7Xkyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
