apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3Z7b/LcdW8rdX/nS9g==,iv:bs4fK1kAKMUCbIySa15HT7hKy+jnJXqVPD3eG5HY/lM=,tag:Wix4nDxokb0jF45kTZK2Ow==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mpD4LOHa13WfvZrkf46E65XDmH55R6jLaA==,iv:pKz8gr8HPKCKB5ZlSEtU5K6svZTwAOznEGo12+sP0iM=,tag:0O4hzUKtwqFkg+vhjgyWdQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4Tv9sQgqCrWjkmX37QqpYu7RKBNjVJIPQXP/csBYGZw3dE2k,iv:MmbJF+Z+3xj2O+WEK0B3kbKXm5rwPGP5x/0e7pU+Ruo=,tag:m9oWBNnOO9E0lDiXt5YipA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yquhz76hg30kccyycwjzj2zxhz5f4phllu470yp9ltjee97wrd2sgkmz0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMnRSYTdFSDZMMUdFMnJY
            aWRNS0NXUURsdURkVWxyZWkrM3pFODdiaUVzCkg4a2ZXVDJScklLdUJCQXh0Wlht
            WXNGemhLaEl4MzlEOW9wNFcxS2s2RWcKLS0tICtOcElmRko4S2dhVHp2aWdwc2o5
            YUJiNEZVcFMweGRqMlRhNnZ0eFY0Y0UKWrAVk4yvJxALkezK1crDKfyeOWPS09rB
            VdxmKOe+OoC5LGQ8NQIUzCCw8O9v+AekZEf2Q/cd81sQLPT5SrFwFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T02:42:25Z"
    mac: ENC[AES256_GCM,data:gwxncg+FNxTkz/yk0JG0+0iWIDsBhp9vqHuT9HI60j2ruHQ6sdG0o8npEpWUL/OtO2cLcEzMVhgw+Gjrv5dfPA1V7MEEJoUqiVrTSPPeUiq5Pa6g85mPNkuYYohqcHTXzIAtLqY+PJn+Mw7OJoaj9Vl2LSPbA60z+IzQsEwi/Yk=,iv:Wn6fm0e9npbdjjFA95jD1KHkywGZbKbgjmMS1AT8j84=,tag:we0VQKY/dQHzjr5vVsqJZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
