apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:bh/KRlUya5PKzk8t0Gfs,iv:vK2gqwiWyHnGCBuegDazM3KFHSsGRV9bMcAc657RwhY=,tag:/ksY9Fg5Q6yn4/ckVLKGnQ==,type:str]
    SECRET_DOMAIN_PERSONAL: ENC[AES256_GCM,data:eg+uzI78EmVoHTT1kf7Fr7OHow==,iv:tsxxj1AQl+xJUR52fxCyGgLQwvKxrfqwmqC6xlA4QcA=,tag:hp1Y1qkpqlXCVw3NUsdX8A==,type:str]
    SECRET_DOMAIN_PUBLIC: ENC[AES256_GCM,data:L+KRbtF1A6PLrGuAzA==,iv:8d8aJBnlfkxnQno3xIdc74vgMDIU+9G+SA9FK8Y3soE=,tag:blD4qhxrvVAKxiPGhQlnFA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tP/v3B+7ZnfKDPu5R/tjz6tm0ZFpWvYb3A==,iv:oLnwsRK7fOYYzGSihOO5M98ythWqa9ljBkQZWVEVJ2k=,tag:9dLKYejrCdvPk2s2zlCSbQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZFvPAMuKlv1iHzAvKSBavkBsKF9W9OObktERMyZOujygJrcs,iv:PV2hhIp6Un9PFfZ+3GFiNTImdNdCpr9yVyVRjLQupW8=,tag:Snwx4XPJ3KEYP5AP9Lv2Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sms0pnuz0hylr53gvj49mt3vvfypsg572lu2lh3fajvlkmp2gpuq9y5yk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3STFQTHpuMFRiNkpvd210
            dW80RUFZL1VEWmJmWWdSbnpWQkJuN2NzSmxNCkxGZitrNktCNVZkRE95UVIxUk83
            V2ZRRGpmSUQ5Sko2bUUxZVdPV1ROaEEKLS0tICsyZW42TVJ5UkhTaHVNbUdlTXgw
            Z1B4RTM1OWlmejIzcUdvc0x4OGlUZ3MK983h8orXwrMpZrBpftabqPA8CUlI3pa/
            NWoXvPl6mzP5UBuhzPubQseOAK9xktdSk3dATEBiulqxo1Wu0oOc0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T06:08:38Z"
    mac: ENC[AES256_GCM,data:mCNszuyBD6V05vJuKDj7gSR7psAkhIIXVZ0GkvCsKiaArA/F3MAhNSoOu43EqS2Yv1IxRk3XITyDZGchBixm2utbvq6oSh914OT17pwa4V9XPd7W9iAZTwSQz/L1+n7GNnetDxKyIfStxjz78Nx8S5QPMkr3XlWs3sZUow0ChPc=,iv:caSuNxRvZF2lfBaHWCrHP00cYKxdlqj2sye+eoRiCuk=,tag:AapYz6nmjk0tpXzQ3MiQCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
