---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-microservices
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: immich-server
      namespace: selfhosted
  values:
    controllers:
      immich-microservices:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.117.0@sha256:ac9fb82f2be3cc60d4e0c7f1ceb371d401d52573e387834d7a82776116458242
            env:
              TZ: ${TIMEZONE}
              IMMICH_WORKERS_EXCLUDE: api
            envFrom:
              - configMapRef:
                  name: immich-configmap
              - secretRef:
                  name: immich-secret
              - secretRef:
                  name: immich-db-secret
            resources:
              requests:
                cpu: 10m
                amd.com/gpu: 1
                memory: 512Mi
              limits:
                amd.com/gpu: 1
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          nodeSelector:
            feature.node.kubernetes.io/pci-0300_1002.present: "true"
    persistence:
      library:
        enabled: true
        type: nfs
        server: ${HOLY_GRAIL_SERVER}
        path: /mnt/user/immich
        globalMounts:
          - path: /usr/src/app/upload
      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri

