---
title: Dashboard
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
useEqualHeights: true
theme: dark
background:
  image: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/101518784_p0.jpg
  opacity: 20
color: slate
headerStyle: clean
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
layout:
  Network:
    style: row
    columns: 3
    icon: mdi-network
  Games:
    style: row
    columns: 3
    icon: mdi-minecraft
  Calendar:
    style: column
    icon: mdi-calendar
  Video:
    style: column
    icon: mdi-play-circle
  Books:
    style: row
    columns: 2
    icon: mdi-book
  Infrastructure:
    style: row
    columns: 5
    icon: mdi-server
  Observability:
    style: row
    columns: 5
    icon: mdi-chart-line
  Home:
    style: row
    columns: 5
    icon: mdi-home-analytics
  Downloads:
    style: row
    columns: 3
    icon: mdi-download-circle
