---
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
useEqualHeights: true
color: gray
background:
  image: https://github.com/helpotters/dracula-wallpapers/blob/bd6282d192b6cf8ac4241a69abaa657a0da43e75/illustrations/galaxy/dracula-galaxy-282a36.png?raw=true
  opacity: 30
headerStyle: clean
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
language: en
layout:
  Network:
    style: row
    columns: 3
    icon: mdi-network
  Games:
    style: row
    columns: 3
    icon: mdi-minecraft
  Calendar:
    style: column
    icon: mdi-calendar
  Video:
    style: column
    icon: mdi-play-circle
  Books:
    style: row
    columns: 2
    icon: mdi-book
  Infrastructure:
    style: row
    columns: 5
    icon: mdi-server
  Observability:
    style: row
    columns: 5
    icon: mdi-chart-line
  Home:
    style: row
    columns: 5
    icon: mdi-home-analytics
  Downloads:
    style: row
    columns: 3
    icon: mdi-download-circle
