---
- logo:
    icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/lds-transparent.png
- search:
    provider: [duckduckgo, google]
    focus: false
    target: _blank
- greeting:
    text_size: xl
    text: "Howdy Hey!"
- openmeteo:
    label: Home
    latitude: {{HOMEPAGE_VAR_HASS_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_HASS_LONGITUDE}}
    units: metric
    cache: 5
- datetime:
    text_size: l
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23
