---
- logo:
    icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/lds-transparent.png
- greeting:
    text_size: xl
    text: "Hey!"
- search:
    focus: false
    target: _blank
- openmeteo:
    label: Home
    latitude: {{HOMEPAGE_VAR_HASS_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_HASS_LONGITUDE}}
    units: metric
    cache: 5
