---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    repository: "${APP}-volsync-minio"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-ceph-block}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-10Gi}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: ${VOLSYNC_PUID:-568}
      runAsGroup: ${VOLSYNC_PGID:-568}
      fsGroup: ${VOLSYNC_PGID:-568}
      seccompProfile: {type: "RuntimeDefault"}
    pruneIntervalDays: ${PRUNE:-14}
    retain:
      hourly: ${HOURLY:-24}
      daily: ${DAILY:-10}
      weekly: ${WEEKLY:-5}
      monthly: ${MONTHLY:-3}
    moverResources:
      limits:
        cpu: 500m
        memory: 2Gi
    moverAffinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/created-by: volsync
            namespaceSelector:
              matchExpressions:
                - key: kubernetes.io/metadata.name
                  operator: Exists


